spring:
  application:
    name: learnjpahibernate
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

application:
  primary:
    datasource:
      name: primary
# When using JTA/XA these properties are not needed
#      embeddedDatabaseType: H2
#      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      xa:
        data-source-class-name: org.h2.Driver
      hikari:
        maximum-pool-size: 3
        minimum-idle: 1
        connection-timeout: 30000
    jpa:
      database: H2
      generate-ddl: false
      show-sql: true
      properties:
        hibernate:
          hbm2ddl.auto: validate
          generate_statistics: false
    sql:
     init:
        enabled: true
        schema-locations:
        -  classpath:/schema-primary.sql
        data-locations:
        - classpath:/data-primary.sql

  secondary:
    datasource: 
      name: secondary
# When using JTA/XA these properties are not needed
#      driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
      url: jdbc:derby:memory:testdb;create=true
      username: APP
      password: APP
      xa:
        data-source-class-name: org.apache.derby.jdbc.EmbeddedDriver
      hikari:
        maximum-pool-size: 3
        minimum-idle: 1
        connection-timeout: 30000
    jpa:
      database: DERBY
      generate-ddl: false
      show-sql: true
      properties:
        hibernate:
          hbm2ddl.auto: validate
          generate_statistics: false
    sql:
     init:
        enabled: true
        schema-locations:
        -  classpath:/schema-secondary.sql
        data-locations:
        - classpath:/data-secondary.sql

logging:
  level:
    org.springframework.transaction: DEBUG
    com.arjuna: DEBUG
