
drop table reservation_cabin if exists;

drop table reservation_person if exists;

drop table reservation if exists;

drop table hailing_frequency if exists;

drop table person if exists;

drop table address if exists;

drop table voyage if exists;
    
drop table planet if exists;

drop table cabin if exists;

drop table ship if exists;

create table ship (
    id bigint generated by default as identity(start with 100),
    name VARCHAR(50) not null,
    ship_class VARCHAR(50) not null,
    primary key (id)
);

create table cabin (
    id bigint generated by default as identity(start with 100),
    bed_count INTEGER not null,
    deck_level INTEGER not null,
    price bigint,
    currency varchar(255),
    ship_id bigint not null,
    primary key (id)
);

alter table cabin 
   add constraint FKdki08ep22rxerw4htxtkdt76 
   foreign key (ship_id) 
   references ship;

create table planet (
    id bigint generated by default as identity(start with 100),
    name VARCHAR(50) not null,
    primary key (id)
);

alter table planet 
   add constraint UK_dhelj2sd5e5spyo2flmdhxo6o unique (name);

create table voyage (
    id bigint generated by default as identity(start with 100),
    departure_date date,
    destination_date date,
    departure_planet_id bigint not null,
    destination_planet_id bigint not null,
    ship_id bigint not null,
    primary key (id)
);

alter table voyage 
   add constraint FKdvi267rex3oqldua68anvxtl5 
   foreign key (departure_planet_id) 
   references planet;

alter table voyage 
   add constraint FKkuwg2y6ethms3x7q6cd3r0dmi 
   foreign key (destination_planet_id) 
   references planet;

alter table voyage 
   add constraint FK6nx7tthxihcj7hid0ic543hyv 
   foreign key (ship_id) 
   references ship;

create table address (
    id bigint generated by default as identity(start with 100),
    city VARCHAR(50) not null,
    street VARCHAR(50) not null,
    planet_id bigint not null,
    primary key (id)
);

alter table address 
   add constraint FKs20a6j9nj0joajmyui24opw3e 
   foreign key (planet_id) 
   references planet;

create table person (
    type VARCHAR(20) not null,
    id bigint generated by default as identity(start with 100),
    name VARCHAR(50) not null,
    home_address_id bigint not null,
    ship_id bigint,
    primary key (id)
);

alter table person 
   add constraint UK_bemy93e8a8i6nknj4n21m6fub unique (home_address_id);

alter table person 
   add constraint FKjnkg5jwqrtjt8m4opp8vtpmbq 
   foreign key (home_address_id) 
   references address;

alter table person 
   add constraint FKp4eertvkj92dtbr25ds0pr0rg 
   foreign key (ship_id) 
   references ship;

create table hailing_frequency (
    frequency varchar(255) not null,
    person_id bigint not null,
    primary key (frequency, person_id)
);

alter table hailing_frequency 
   add constraint FKhggd3e5ig2h37vihl6aobffjp 
   foreign key (person_id) 
   references person;

create table reservation (
    id bigint generated by default as identity(start with 100),
    voyage_id bigint not null,
    primary key (id)
);

create table reservation_cabin (
    reservation_id bigint not null,
    cabin_id bigint not null,
    primary key (reservation_id, cabin_id)
);

create table reservation_person (
    reservation_id bigint not null,
    person_id bigint not null,
    primary key (reservation_id, person_id)
);

alter table reservation 
   add constraint FK1s0o59h0ment1tmpk8ewweoxy 
   foreign key (voyage_id) 
   references voyage;

alter table reservation_cabin 
   add constraint FKn3cffgdky9okkuky8926vu4w5 
   foreign key (cabin_id) 
   references cabin;

alter table reservation_cabin 
   add constraint FKooapvjuc3cuq5u0wa7inx4xv8 
   foreign key (reservation_id) 
   references reservation;

alter table reservation_person 
   add constraint FK50ng078c332d5jicm1wm2sf91 
   foreign key (person_id) 
   references person;

alter table reservation_person 
   add constraint FKrjgmu6ic1kii9ykb3fgkd7mqj 
   foreign key (reservation_id) 
   references reservation;
