---
spring:
  application:
    name: learnjpahibernate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    database: H2
    properties:
      eclipselink.weaving: false
      # ddl-generate values include: create-tables, drop-and-create-tables, none
      eclipselink.ddl-generation: none

      # the following settings can be used to generate schema files from entities
      # https://www.eclipse.org/eclipselink/documentation/2.5/jpa/extensions/p_ddl_generation.htm
      #eclipselink.ddl-generation: drop-and-create-tables
      #eclipselink.create-ddl-jdbc-file-name: create-schema.sql
      #eclipselink.drop-ddl-jdbc-file-name: drop-schema.sql
      #eclipselink.ddl-generation.output-mode: both

      # logging.level.sql values include: SEVERE, WARNING, INFO, FINE, ALL
      eclipselink.logging.level.sql: FINE
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:/schema.sql
      data-locations:
      - classpath:/data.sql

#logging:
  #level:
    #org.springframework.data.jpa: DEBUG
