---
spring:
  application:
    name: learnjpahibernate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    database: H2
    properties:
      # SynchronizeMappings values include: buildSchema(ForeignKeys=true), dropSchema, validate (see MappingTool.java)
      openjpa.jdbc.SynchronizeMappings: validate
      
      # the following settings can be used to log schema from entities
      #openjpa.jdbc.SynchronizeMappings: buildSchema(ForeignKeys=true)
      #openjpa.Log: DefaultLevel=TRACE,SQL=TRACE
      
      # Log values include: TRACE, INFO, WARN, ERROR or FATAL
      openjpa.Log: openjpa.jdbc.SQL=trace

#     openjpa.DynamicEnhancementAgent: false
#     openjpa.RuntimeUnenhancedClasses: unsupported
#     openjpa.jdbc.SynchronizeMappings: buildSchema(ForeignKeys=true) 
  sql:
    init:
      enabled: true
      schema-locations:
      - classpath:/schema.sql
      data-locations:
      - classpath:/data.sql

#logging:
  #level:
    #org.springframework.data.jpa: DEBUG
