---
spring:
  application:
    name: learnjpahibernate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: false
  sql:
    init:
      enabled: true
      schema-locations:
      - classpath:/schema.sql
      data-locations: []

#logging:
  #level:
    #org.springframework.data.jpa: DEBUG
