---
spring:
  application:
    name: learnjpahibernate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
  sql:
    init:
      mode: always
      schema-locations: []
      data-locations: []

#logging:
  #level:
    #org.springframework.data.jpa: DEBUG
