
drop table if exists invoice if exists;

drop table if exists late_invoice;

create table invoice (
    id bigint generated by default as identity,
    name VARCHAR(100) not null,
    account_manager VARCHAR(100) not null,
    primary key (id)
);

create table late_invoice (
    id bigint generated by default as identity,
    name VARCHAR(100) not null,
    review_date DATE not null,
    primary key (id)
);
