
-- https://en.wikipedia.org/wiki/Star_schema

drop table dim_date if exists;

drop table dim_store if exists;

drop table dim_product if exists;

drop table fact_sales if exists;

create table dim_date (
    id bigint generated by default as identity(start with 100),
    fiscal_date date not null,
    primary key (id)
);

alter table dim_date 
   add constraint uk_dim_date_1 unique (fiscal_date);

create table dim_store (
    id bigint generated by default as identity(start with 100),
    store_number VARCHAR(50) not null,
    primary key (id)
);

alter table dim_store
   add constraint uk_dim_store_1 unique (store_number);

create table dim_product (
    id bigint generated by default as identity(start with 100),
    product_name VARCHAR(100) not null,
    primary key (id)
);

alter table dim_product
   add constraint uk_dim_product_1 unique (product_name);

create table fact_sales (
    date_id bigint not null,
    store_id bigint not null,
    product_id bigint not null,
    units_sold bigint not null,
    primary key (date_id, store_id, product_id)
);

alter table fact_sales 
   add constraint fk_fact_sales_1
   foreign key (date_id) 
   references dim_date;

alter table fact_sales 
   add constraint fk_fact_sales_2
   foreign key (store_id) 
   references dim_Store;

alter table fact_sales 
   add constraint fk_fact_sales_3
   foreign key (product_id) 
   references dim_product;

create view fact_sales_view as
select f.date_id, d.fiscal_date, f.store_id, s.store_number, f.product_id, p.product_name, f.units_sold
from fact_sales f
inner join dim_date d    on (f.date_id = d.id)
inner join dim_store s   on (f.store_id = s.id)
inner join dim_product p on (f.product_id = p.id)
