---
spring:
  application:
    name: learnjpahibernate
  main:
    # Unsure where circle is
    allow-circular-references: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.search.backend.directory.type: local-heap
#     hibernate.search.backend.directory.type: local-filesystem
#     hibernate.search.backend.directory.root: /tmp/learn-jpa-hibernate-lucene
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:/schema.sql
      data-locations:
      - classpath:/data.sql

#logging:
  #level:
    #org.springframework.data.jpa: DEBUG



