
drop table event if exists;

create table event (
    id bigint generated by default as identity(start with 100),
    description VARCHAR(100) not null,
    created_by VARCHAR(100),
    created_date TIMESTAMP,
    last_modified_by VARCHAR(100),
    last_modified_date TIMESTAMP,
    primary key (id)
);
